# Generated by Django 5.0.1 on 2024-02-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receita',
        ),
    ]
