# Generated by Django 5.0.1 on 2024-01-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ingrediente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='selecionado',
            field=models.BooleanField(default=False),
        ),
    ]
