# Generated by Django 5.0.1 on 2024-01-31 15:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ingrediente_selecionado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='selecionado',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='receita',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='receitafavorita',
            unique_together={('usuario', 'receita')},
        ),
        migrations.CreateModel(
            name='UsuarioIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingrediente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'ingrediente')},
            },
        ),
    ]
