# Generated by Django 5.0.1 on 2024-01-31 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_ingrediente_selecionado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
