# Generated by Django 5.0.1 on 2024-03-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_delete_receitafavorita'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemreceita',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
