# Generated by Django 5.0.1 on 2024-03-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_imagemreceita_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemreceita',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='receitas/'),
        ),
    ]
