# Generated by Django 5.0.1 on 2024-03-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_imagemreceita_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='aprovada',
            field=models.BooleanField(default=False),
        ),
    ]
