# Generated by Django 5.0.1 on 2024-03-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_receita_aprovada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='instrucoes',
            new_name='instruções',
        ),
    ]
